//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace magazaproje3
{
    using System;
    using System.Collections.Generic;
    
    public partial class bolumler
    {
        public int bolumno { get; set; }
        public Nullable<int> sorumluno { get; set; }
        public string bolumadi { get; set; }
        public Nullable<int> bolumurunsayisi { get; set; }
    }
}
