//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace magazaproje3
{
    using System;
    using System.Collections.Generic;
    
    public partial class magaza
    {
        public int magazano { get; set; }
        public string magazaadi { get; set; }
        public string magazaciro { get; set; }
        public string magazaadres { get; set; }
        public string sevkiyattarih { get; set; }
        public string sevkiyatgunu { get; set; }
    }
}
