//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace magazaproje3
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class magazalarEntities : DbContext
    {
        public magazalarEntities()
            : base("name=magazalarEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bolumler> bolumlers { get; set; }
        public virtual DbSet<kullanicilar> kullanicilars { get; set; }
        public virtual DbSet<magaza> magazas { get; set; }
        public virtual DbSet<malzeme> malzemes { get; set; }
        public virtual DbSet<sorumlu> sorumlus { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
