//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace magazaproje3
{
    using System;
    using System.Collections.Generic;
    
    public partial class malzeme
    {
        public int malzemeno { get; set; }
        public Nullable<int> magazano { get; set; }
        public string malzemeadi { get; set; }
        public Nullable<int> malzemeadet { get; set; }
        public Nullable<decimal> malzemebirimfiyat { get; set; }
        public string malzemekod { get; set; }
        public string malzemeaciklama { get; set; }
    }
}
