//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace magazaproje3
{
    using System;
    using System.Collections.Generic;
    
    public partial class sorumlu
    {
        public int sorumluno { get; set; }
        public Nullable<int> magazano { get; set; }
        public string sorumluadi { get; set; }
        public Nullable<decimal> sorumlumaas { get; set; }
        public Nullable<decimal> sorumluprim { get; set; }
        public string sorumluvardiya { get; set; }
    }
}
